package com.doing.server.pojo;

// Generated Aug 24, 2015 10:35:45 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Comment generated by hbm2java
 */
@Entity
@Table(name = "comment", catalog = "murat")
public class Comment implements java.io.Serializable {

	private Integer id;
	private String comment;
	private int taskid;
	private int userid;

	public Comment() {
	}

	public Comment(String comment, int taskid, int userid) {
		this.comment = comment;
		this.taskid = taskid;
		this.userid = userid;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "comment", nullable = false, length = 256)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "taskid", nullable = false)
	public int getTaskid() {
		return this.taskid;
	}

	public void setTaskid(int taskid) {
		this.taskid = taskid;
	}

	@Column(name = "userid", nullable = false)
	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

}
